application:
  host: 'localhost'
  port: 3000

db:
  mysql:
    host: 'localhost'
    port: 3306
    database: 'interview_question_bank'
    username: 'root'
    password: '123456'
  redis:
    host: 'localhost'
    port: 6379

email:
  host: "smtp.qq.com"
  port: 587,
  user: 
  pass: 